### This Chart.yaml file is used for local testing purposes
### If you want to test the chart before creating PR, rename this file into Chart.yaml and test the deployment

apiVersion: v2
name: airbyte
description: Helm chart to deploy airbyte


# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: dev

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - condition: airbyte-bootloader.enabled
    name: airbyte-bootloader
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: temporal.enabled
    name: temporal
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: temporal-ui.enabled
    name: temporal-ui
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: webapp.enabled
    name: webapp
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: server.enabled
    name: server
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: worker.enabled
    name: worker
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: workload-api-server.enabled
    name: workload-api-server
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: workload-launcher.enabled
    name: workload-launcher
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: pod-sweeper.enabled
    name: pod-sweeper
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: metrics.enabled
    name: metrics
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: cron.enabled
    name: cron
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: connector-builder-server.enabled
    name: connector-builder-server
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: connector-rollout-worker.enabled
    name: connector-rollout-worker
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: keycloak.enabled
    name: keycloak
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
  - condition: keycloak-setup.enabled
    name: keycloak-setup
    repository: https://airbytehq.github.io/helm-charts/
    version: 1.1.0
