{{- if .Values.global.airbyteYml }}
# The Secret that contains the airbyte.yml content. For this to work helm must be started with
# --set-file global.airbyteYml=<path_to_configs>/airbyte.yml
# For Airbyte Enterprise our installation script automatically specifies this, for Community
# users will need to specify it, if they want to use the airbyte.yml config file.
# If nothing is specified we'll assume an empty config
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-airbyte-yml
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
type: Opaque
data:
  fileContents: "{{ .Values.global.airbyteYml | default "" | nindent 4 | b64enc }}"
{{- end }}
