{{- if eq .Values.global.deploymentMode "oss"  }}
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "airbyte.serviceAccountName" . }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-10"
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "airbyte.serviceAccountName" . }}-role
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-5"
rules:
  - apiGroups: ["*"]
{{- if eq .Values.global.edition "community" }}
    resources: ["jobs", "pods", "pods/log", "pods/exec", "pods/attach", "secrets"]
{{- else }}
    resources: ["jobs", "pods", "pods/log", "pods/exec", "pods/attach"]
{{- end }}
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] # over-permission for now
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "airbyte.serviceAccountName" . }}-binding
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-3"
roleRef:
  apiGroup: ""
  kind: Role
  name: {{ include "airbyte.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "airbyte.serviceAccountName" . }}
---
{{- if not (default false .Values.serviceAccount.denyNodeViewerRole) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  name: node-viewer
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  name: {{ include "airbyte.serviceAccountName" . }}-admin-node-viewer
subjects:
  - kind: ServiceAccount
    name: {{ include "airbyte.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: node-viewer
  apiGroup: rbac.authorization.k8s.io
{{- end }}
{{- end }}
{{- end }}
