# Create dataplane secrets only for the local deployment
{{- if .Values.global.local }}
apiVersion: v1
kind: Secret
metadata:
  name: workload-launcher-secrets
  namespace: {{ include "airbyte.jobs.kube.namespace" . }}
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
type: Opaque
stringData:
  {{- include "airbyte.secretsManager.secrets" . | nindent 2 }}
  {{- include "airbyte.storage.secrets" . | nindent 2 }}

{{- end }}
