{{- if .Values.server.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
    {{- if .Values.server.extraLabels }}
    {{ toYaml (mergeOverwrite .Values.server.extraLabels .Values.global.extraLabels) | nindent 4 }}
    {{- end }}
  annotations:
    {{ toYaml .Values.server.annotations | nindent 4 }}
spec:
  minReadySeconds: 30
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "airbyte.selectorLabels" . | nindent 6 }}
      {{- if .Values.server.extraSelectorLabels }}
      {{ toYaml (mergeOverwrite .Values.server.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 6 }}
      {{- end }}
  strategy:
    type: {{ .Values.server.deploymentStrategyType }} # Needed due to volume claims
  template:
    metadata:
      labels:
        {{- include "airbyte.selectorLabels" . | nindent 8 }}
        {{- if .Values.server.extraSelectorLabels }}
        {{ toYaml (mergeOverwrite .Values.server.extraSelectorLabels .Values.global.extraSelectorLabels) | nindent 8 }}
        {{- end }}
        {{- if .Values.server.podLabels }}
          {{- include "airbyte.tplvalues.render" (dict "value" .Values.server.podLabels "context" $) | nindent 8 }}
        {{- end }}
      {{- if .Values.server.podAnnotations }}
      annotations:
        {{- include "airbyte.tplvalues.render" (dict "value" .Values.server.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ default .Values.global.serviceAccountName .Values.server.serviceAccountName }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
          {{- printf "- name: %s" .name | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.server.nodeSelector }}
      nodeSelector: {{- include "airbyte.tplvalues.render" (dict "value" .Values.server.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.tolerations }}
      tolerations: {{- include "airbyte.tplvalues.render" (dict "value" .Values.server.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.affinity }}
      affinity: {{- include "airbyte.tplvalues.render" (dict "value" .Values.server.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.server.extraInitContainers }}
      initContainers:
      {{- toYaml .Values.server.extraInitContainers | nindent 6 }}
      {{- end }}
      containers:
      - name: airbyte-server-container
        image: {{ include "imageUrl" (list .Values.server.image $) }}
        imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
        env:
        {{- if .Values.server.debug.enabled }}
        - name: JAVA_TOOL_OPTIONS
          value: "-Xdebug -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:{{ .Values.server.debug.remoteDebugPort }},server=y,suspend=n"
        {{- end}}

        {{- if (or (eq .Values.global.edition "community") (eq .Values.global.edition "enterprise")) }}
        {{- include "airbyte.auth.envs" . | nindent 8 }}
        {{- end}}

        {{- if (eq .Values.global.edition "community") }}
        {{- include "airbyte.auth.security.envs" . | nindent 8 }}
        {{- end }}

        {{- include "airbyte.auth.jwt.envs" . | nindent 8 }}
        {{- include "airbyte.common.envs" . | nindent 8 }}
        {{- include "airbyte.cluster.envs" . | nindent 8 }}
        {{- include "airbyte.connector.envs" . | nindent 8 }}
        {{- include "airbyte.customerio.envs" . | nindent 8 }}
        {{- include "airbyte.database.envs" . | nindent 8 }}
        {{- include "airbyte.database.migrations.envs" . | nindent 8 }}
        {{- include "airbyte.dataplaneGroups.envs" . | nindent 8 }}
        {{- include "airbyte.jobs.envs" . | nindent 8 }}
        {{- include "airbyte.jobs.errors.envs" . | nindent 8 }}
        {{- include "airbyte.jobs.scheduling.envs" . | nindent 8 }}
        {{- include "airbyte.logging.envs" . | nindent 8 }} 
        {{- include "airbyte.metrics.envs" . | nindent 8 }}
        {{- include "airbyte.micronaut.envs" . | nindent 8 }}
        {{- include "airbyte.secretsManager.envs" . | nindent 8 }}
        {{- include "airbyte.server.envs" . | nindent 8 }}
        {{- include "airbyte.storage.envs" . | nindent 8 }}
        {{- include "airbyte.temporal.envs" . | nindent 8 }}
        {{- include "airbyte.tracking.envs" . | nindent 8 }}
        {{- include "airbyte.worker.envs" . | nindent 8 }}
        {{- include "airbyte.workloads.resources.envs" . | nindent 8 }}
        {{- include "airbyte.connectorBuilder.envs" . | nindent 8 }}

        {{- if .Values.global.datadog.enabled }}
        - name: DD_SERVICE 
          value: {{ include "airbyte.componentNameWithAirbytePrefix" . }}
        {{- include "airbyte.datadog.envs" . | nindent 8 }}
        {{- include "airbyte.otel.envs" . | nindent 8 }}
        {{- end}}

        {{- if (eq .Values.global.edition "enterprise") }}
        {{- include "airbyte.auth.instanceAdmin.enterprise.envs" . | nindent 8 }} 
        {{- include "airbyte.auth.identityProvider.envs" . | nindent 8 }} 
        {{- include "airbyte.enterprise.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.admin.client.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.admin.user.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.client.envs" . | nindent 8 }}
        {{- else if (eq .Values.global.edition "cloud") }}
        {{- include "airbyte.aws.envs" . | nindent 8 }}
        {{- include "airbyte.connectorRollout.envs" . | nindent 8 }}
        {{- include "airbyte.featureFlags.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.admin.client.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.admin.user.envs" . | nindent 8 }}
        {{- include "airbyte.keycloak.client.envs" . | nindent 8 }}
        {{- include "airbyte.orb.envs" . | nindent 8 -}}
        {{- include "airbyte.redis.envs" . | nindent 8 -}}
        {{- include "airbyte.stigg.envs" . | nindent 8 }}
        {{- include "airbyte.stripe.envs" . | nindent 8 }}
        {{- include "airbyte.temporal.cloud.envs" . | nindent 8 }}
        {{- include "airbyte.temporal.cloud.billing.envs" . | nindent 8 }}
        {{- include "airbyte.temporal.cloud.connectorRollout.envs" . | nindent 8 }}
        {{- include "airbyte.temporal.cloud.credentials.envs" . | nindent 8 }}
        {{- end}}

        # Values from secret
        {{- if .Values.server.secrets }}
        {{- range $k, $v := .Values.server.secrets }}
        - name: {{ $k }}
          valueFrom:
            secretKeyRef:
              name: server-secrets
              key: {{ $k }}
        {{- end }}
        {{- end }}

        # Values from env
        {{- if or .Values.server.env_vars .Values.global.env_vars }}
        {{- range $k, $v := mergeOverwrite .Values.server.env_vars .Values.global.env_vars }}
        - name: {{ $k }}
          value: {{ $v | quote }}
        {{- end }}
        {{- end }}

        # Values from extraEnv for more compability(if you want to use external secret source or other stuff)
        {{- if .Values.server.extraEnv }}
        {{- toYaml .Values.server.extraEnv | nindent 8 }}
        {{- end }}

        {{- if .Values.server.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: {{ .Values.server.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.server.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.server.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.server.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.server.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.server.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: {{ .Values.server.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.server.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.server.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.server.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.server.readinessProbe.failureThreshold }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8001
          protocol: TCP
        - name: management
          containerPort: {{ .Values.server.management.port }}
          protocol: TCP
        {{- if .Values.server.debug.enabled }}
        - name: debug
          containerPort: {{ .Values.server.debug.remoteDebugPort }}
          protocol: TCP
        {{- end}}
        {{- if .Values.server.resources }}
        resources: {{- toYaml .Values.server.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.server.containerSecurityContext }}
        securityContext: {{- toYaml .Values.server.containerSecurityContext | nindent 10 }}
        {{- end }}
        volumeMounts:
        {{- if eq (include "airbyte.storage.type" .) "gcs" }}
        - name: gcs-log-creds-volume
          mountPath: {{ include "airbyte.storage.gcs.credentialsJsonPath" . | dir }}
          readOnly: true
         {{- else if eq (lower (include "airbyte.storage.type" .)) "local" }}
        - name: airbyte-storage
          mountPath: /storage
        {{- end }}

        {{- if .Values.server.extraVolumeMounts }}
          {{ toYaml .Values.server.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if .Values.global.extraVolumeMounts }}
          {{ toYaml .Values.global.extraVolumeMounts | nindent 8 }}
        {{- end }}
      {{- if .Values.server.extraContainers }}
        {{ toYaml .Values.server.extraContainers | nindent 6 }}
      {{- end }}
      {{- if .Values.global.extraContainers }}
        {{ toYaml .Values.global.extraContainers | nindent 6 }}
      {{- end }}
      securityContext: {{- toYaml .Values.server.podSecurityContext | nindent 8 }}
      volumes:
      {{- if eq (include "airbyte.storage.type" .) "gcs" }}
      - name: gcs-log-creds-volume
        secret:
          secretName: {{ include "airbyte.storage.secretName" . }}
          items:
            - key: {{ include "airbyte.storage.gcs.credentialsJson.secretKey" . }}
              path: "gcp.json"
      {{- else if eq (lower (include "airbyte.storage.type" .)) "local" }}
      - name: airbyte-storage
        persistentVolumeClaim:
          claimName: airbyte-storage-pvc
      {{- end }}

      {{- if .Values.server.extraVolumes }}
      {{ toYaml .Values.server.extraVolumes | nindent 6 }}
      {{- end }}
{{- end }}
