apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-airbyte-env
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-1"
  labels:
    {{- include "airbyte.labels" . | nindent 4 }}
data:
  {{- include "airbyte.auth.bootstrap.configVars" . | nindent 2 }}
  {{- include "airbyte.auth.identityProvider.configVars" . | nindent 2 }}
  {{- include "airbyte.auth.instanceAdmin.enterprise.configVars" . | nindent 2 }}
  {{- include "airbyte.auth.security.configVars" . | nindent 2 }}
  {{- include "airbyte.aws.configVars" . | nindent 2 }}
  {{- include "airbyte.cluster.configVars" . | nindent 2 }}
  {{- include "airbyte.common.configVars" . | nindent 2 }}
  {{- include "airbyte.connector.configVars" . | nindent 2 }}
  {{- include "airbyte.connectorBuilder.configVars" . | nindent 2 }}
  {{- include "airbyte.connectorRollout.configVars" . | nindent 2 }}
  {{- include "airbyte.cron.configVars" . | nindent 2 }}
  {{- include "airbyte.database.configVars" . | nindent 2 }}
  {{- include "airbyte.database.migrations.configVars" . | nindent 2 }}
  {{- include "airbyte.datadog.configVars" . | nindent 2 }}
  {{- include "airbyte.dataplaneGroups.configVars" . | nindent 2 }}
  {{- include "airbyte.featureFlags.configVars" . | nindent 2 }}
  {{- include "airbyte.java.configVars" . | nindent 2 }}
  {{- include "airbyte.jobs.configVars" . | nindent 2 }}
  {{- include "airbyte.jobs.scheduling.configVars" . | nindent 2 }}
  {{- include "airbyte.jobs.errors.configVars" . | nindent 2 }}
  {{- include "airbyte.keycloak.admin.client.configVars" . | nindent 2 }}
  {{- include "airbyte.keycloak.client.configVars" . | nindent 2 }}
  {{- include "airbyte.keycloak.configVars" . | nindent 2 }}
  {{- include "airbyte.keycloak.database.configVars" . | nindent 2 }}
  {{- include "airbyte.logging.configVars" . | nindent 2 }}
  {{- include "airbyte.metrics.configVars" . | nindent 2 }}
  {{- include "airbyte.micronaut.configVars" . | nindent 2 }}
  {{- include "airbyte.otel.configVars" . | nindent 2 }}
  {{- include "airbyte.secretsManager.configVars" . | nindent 2 }}
  {{- include "airbyte.server.configVars" . | nindent 2 }}
  {{- include "airbyte.stigg.configVars" . | nindent 2 }}
  {{- include "airbyte.storage.configVars" . | nindent 2 }}
  {{- include "airbyte.temporal.cli.configVars" . | nindent 2 }}
  {{- include "airbyte.temporal.cloud.configVars" . | nindent 2 }}
  {{- include "airbyte.temporal.configVars" . | nindent 2 }}
  {{- include "airbyte.temporal.database.configVars" . | nindent 2 }}
  {{- include "airbyte.temporal.sdk.configVars" . | nindent 2 }}
  {{- include "airbyte.temporal.worker.configVars" . | nindent 2 }}
  {{- include "airbyte.topology.configVars" . | nindent 2 }}
  {{- include "airbyte.tracking.configVars" . | nindent 2 }}
  {{- include "airbyte.webapp.configVars" . | nindent 2 }}
  {{- include "airbyte.worker.configVars" . | nindent 2 }}
  {{- include "airbyte.workloadApiServer.configVars" . | nindent 2 }}
  {{- include "airbyte.workloadLauncher.configVars" . | nindent 2 }}
  {{- include "airbyte.workloadLauncher.dataPlane.configVars" . | nindent 2 }}
  {{- include "airbyte.workloadLauncher.images.configVars" . | nindent 2 }}
  {{- include "airbyte.workloads.configVars" . | nindent 2 }}
  {{- include "airbyte.workloads.queues.configVars" . | nindent 2 }}
  {{- include "airbyte.workloads.resources.configVars" . | nindent 2 }}

  {{- include "airbyte.extra.configVars" . | nindent 2 }}

  LAUNCHER_MICRONAUT_ENVIRONMENTS: "control-plane,oss"
  WORKERS_MICRONAUT_ENVIRONMENTS: "control-plane"
  CRON_MICRONAUT_ENVIRONMENTS: "control-plane"
  SERVER_MICRONAUT_ENVIRONMENTS: "control-plane"
